---
build_from:
  armv7: "ghcr.io/hassio-addons/debian-base/armv7:6.2.3"
  aarch64: "ghcr.io/hassio-addons/debian-base/aarch64:6.2.3"
  amd64: "ghcr.io/hassio-addons/debian-base/amd64:6.2.3"
  i386: "ghcr.io/hassio-addons/debian-base/i386:6.2.3"
