---
build_from:
  armv7: "ghcr.io/hassio-addons/debian-base/armv7:stable"
  aarch64: "ghcr.io/hassio-addons/debian-base/aarch64:stable"
  amd64: "ghcr.io/hassio-addons/debian-base/amd64:stable"
  i386: "ghcr.io/hassio-addons/debian-base/i386:stable"
