---
name: Release Drafter

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  workflows:
    uses: coostax/ghactions-workflows/.github/workflows/release-drafter.yaml@main
